name:                elmish-wasm
version:             0.1.0.0
github:              "chadtech/elmish-wasm"
license:             BSD3
author:              "Chadtech"
maintainer:          "chadtech0@gmail.com"
copyright:           "2017 Chadtech"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/elmish-wasm#readme>

dependencies:
- base >= 4.7 && < 5
- flow
- text
- regex-posix
- split
- bytestring
- ilist

library:
  source-dirs: src


executables:
  elmish-wasm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elmish-wasm

tests:
  elmish-wasm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elmish-wasm
